# Generated by Django 5.1.12 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="summary_message_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="summary_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
