# Generated by Django 5.2.14 on 2026-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatlog",
            new_name="manager_cha_created_91372b_idx",
            old_name="manager_cha_created_idx",
        ),
        migrations.RenameIndex(
            model_name="chatlog",
            new_name="manager_cha_halluci_1bcae7_idx",
            old_name="manager_cha_hallu_idx",
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
