# Generated by Django 5.2.14 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_rename_manager_cha_created_idx_manager_cha_created_91372b_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticCacheEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("sources", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, default="", max_length=120)),
                ("vector_point_id", models.CharField(blank=True, default="", max_length=80)),
                ("similarity", models.FloatField(blank=True, null=True)),
                ("hit_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="manager_sem_created_1ef41d_idx"),
                    models.Index(fields=["expires_at"], name="manager_sem_expires_6fbb51_idx"),
                    models.Index(fields=["model_name"], name="manager_sem_model_n_27a822_idx"),
                ],
            },
        ),
    ]
